name: Node.js Test Runner

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 19
      uses: actions/setup-node@v1
      with:
        node-version: 19

    - run: npm install

    - run: npm run build

    - run: npm test
